routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

//Route::get('/', function () {
//    return view('welcome');
//});

Auth::routes();

    Route::get('/home', ['as' => 'index', 'uses' => 'IndexController@showIndex']);
    Route::get('/contact', ['as' => 'contact', 'uses' => 'IndexController@contact']);
    Route::get('/messages/{email}', ['as' => 'messages', 'uses' => 'ContactController@messages']);

    Route::get('/adminMap', 'ZoneController@show');
    Route::get('/clientMap', 'ZoneController@showClient');
    Route::get('/', ['as' => 'index', 'uses' => 'IndexController@showIndex']);
    Route::post('send', ['as' => 'send', 'uses' => 'ContactController@send']);
//
Route::get('/deleteMsg/{id}',['as'=>'deleteMsg','uses'=>'ContactController@delete']);

    Route::get('/categ', ['as' => 'listing', 'uses' => 'CategorieController@showCategorie']);

    //Route::get('/home', 'HomeController@index')->name('home');
    Route::get('/home', ['as' => 'index', 'uses' => 'IndexController@showIndex']);

    Route::get('/map', 'map@show');
    Route::get('/profile', 'profileController@showProfile');

    Route::get('/', ['as' => 'index', 'uses' => 'IndexController@showIndex']);


    Route::get('/categ', ['as' => 'listing', 'uses' => 'CategorieController@showCategorie']);

//Route::get('/editCateg',['as'=>'listing','uses'=>'CategorieController@editCategorie']);
//Route::get('/addCateg',['as'=>'listing','uses'=>'CategorieController@addCategorie']);

    Route::get('/listProd', ['as' => 'listing', 'uses' => 'ProduitController@showProduit']);


    Route::get('/editProd/{id}', ['as' => 'listing', 'uses' => 'ProduitController@edit']);
    Route::post('/editProd/{id}', 'ProduitController@update');
    Route::post('/modif/{id}', 'OrdersController@modif');

    Route::get('/addProd', ['as' => 'listing', 'uses' => 'ProduitController@addProduit']);
    Route::post('/addProd', 'ProduitController@store');

//Route::get('/delete/{id}',['as'=>'listing','uses'=>'ProduitController@destroy']);
//Route::ressource('produit','ProduitController');

    Route::delete('/delete/{id}', 'ProduitController@destroy');
    Route::get('/order', 'OrdersController@show');


    Route::get('/editProd', ['as' => 'listing', 'uses' => 'ProduitController@editProduit']);
    Route::get('/addProd', ['as' => 'listing', 'uses' => 'ProduitController@addProduit']);
    Route::resource('categorie', 'CategorieController');
    Route::resource('zone', 'ZoneController');
    Route::resource('payment', 'PaymentMethodController');

    Route::delete('/delete/{id}', 'ProduitController@destroy');
    Route::get('/recette', 'RecetteController@show');
    Route::post('/filter', 'RecetteController@filter');
    Route::resource('categorie', 'CategorieController');
    Route::resource('orders', 'OrdersController');
    Route::resource('users', 'UsersController');
//Route::get('/find/{id}','UsersController@find');

    Route::get('/find/{id}', ['as' => 'find', 'uses' => 'UsersController@find']);
    Route::post('/profileSetting/{id}', ['as' => 'profileSetting', 'uses' => 'profileController@profileSetting']);
    Route::post('/changePassword/{id}', ['as' => 'changePassword', 'uses' => 'profileController@changePassword']);
//Route::resource('recette', 'RecetteController');
    Route::get('/showlivre', 'OrdersController@showLivre');

resources/views/Module/map.blade.php
@extends('layouts/app')
@section('title','map')
@section('topCss')
    @parent

@endsection

@section('topJs')
    @parent

@endsection
@section("header")
    @parent

@endsection
@section("menu")
    @parent

@endsection
@section('content')
    <section class="content">
        <div class="container-fluid">
            <div class="block-header">
                <h2>DASHBOARD</h2>
            </div>

        @section("clientMap")

            @include("partiels.clientMap")

        @show
            @section("adminMap")

                @include("partiels.adminMap")

            @show


        </div>
    </section>
@endsection
@section("footerJs")
    @parent


@endsection

resources/views/Module/profile.blade.php
@extends('layouts/app')
@section('title','profile')
@section('topCss')
    @parent

@endsection

@section('topJs')
    @parent

@endsection
@section("header")
    @parent

@endsection
@section("menu")
    @parent

@endsection
@section('content')
<section class="content">
    <div class="container-fluid">
        <div class="row clearfix">
            <div class="col-xs-12 col-sm-3">
                <div class="card profile-card">
                    <div class="profile-header">&nbsp;</div>
                    <div class="profile-body">
                        <div class="image-area">
                            <img src="../../images/user-lg.jpg" alt="AdminBSB - Profile Image" />
                        </div>
                        <div class="content-area">
                            <h3>{{ Auth::user()->name }}</h3>
                            <p>Web Software Developer</p>
                            <p>Administrator</p>
                        </div>
                    </div>

                </div>


            </div>
            <div class="col-xs-12 col-sm-9">
                <div class="card">
                    <div class="body">
                        <div>
                            @if($errors->any())
                                <div class="alert alert-danger">
                                    <ul>
                                        @foreach($errors->all() as $error)
                                            <li>{{$error}}</li>
                                        @endforeach
                                    </ul>
                                </div><br/>
                            @endif
                                @if(session()->get('success'))
                                    <div class="alert alert-success">
                                        {{ session()->get('success') }}
                                    </div><br />
                                @endif
                            <ul class="nav nav-tabs" role="tablist">
                                <li role="presentation" class="active"><a href="#profile_settings" aria-controls="settings" role="tab" data-toggle="tab">Profile Settings</a></li>
                                <li role="presentation"><a href="#change_password_settings" aria-controls="settings" role="tab" data-toggle="tab">Change Password</a></li>
                            </ul>

                            <div class="tab-content">



                                <div role="tabpanel" class="tab-pane fade in active" id="profile_settings">
                                    <form id="form_advanced_validation" novalidate="novalidate" class="form-horizontal"action="{{action('profileController@profileSetting',Auth::user()->id )}}" method="post">
                                        @csrf
                                        <div class="form-group">
                                            <label for="NameSurname" class="col-sm-2 control-label">Name Surname</label>
                                            <div class="col-sm-10">
                                                <div class="form-line">
                                                    <input type="text" class="form-control"   name="name" placeholder="Name Surname" value="{{ Auth::user()->name }}" required="" aria-required="true">
                                                </div>
                                            </div>
                                        </div>
                                        <div class="form-group">
                                            <label for="Email" class="col-sm-2 control-label">Email</label>
                                            <div class="col-sm-10">
                                                <div class="form-line">
                                                    <input type="email" class="form-control"  name="email" placeholder="Email" value="{{ Auth::user()->email }}" required="" aria-required="true">
                                                </div>
                                            </div>
                                        </div>


                                        <div class="form-group">
                                            <div class="col-sm-offset-2 col-sm-10">
                                                <button type="submit" class="btn btn-danger">SUBMIT</button>
                                            </div>
                                        </div>
                                    </form>
                                </div>


                                <div role="tabpanel" class="tab-pane fade in" id="change_password_settings">

                                    <form class="form-horizontal"action="{{action('profileController@changePassword',Auth::user()->id )}}" method="post">
                                        @csrf
                                        <div class="form-group">
                                            <label  class="col-sm-3 control-label">Old Password</label>
                                            <div class="col-sm-9">
                                                <div class="form-line">
                                                    <input type="password" class="form-control"   name="old" placeholder="Old Password" required="" aria-required="true">
                                                </div>
                                            </div>
                                        </div>
                                        <div class="form-group">
                                            <label for="NewPassword" class="col-sm-3 control-label">New Password</label>
                                            <div class="col-sm-9">
                                                <div class="form-line">
                                                    <input type="password" class="form-control" name="new" placeholder="New Password" required="" aria-required="true">
                                                </div>
                                            </div>
                                        </div>
                                        <div class="form-group">
                                            <label for="NewPasswordConfirm" class="col-sm-3 control-label">New Password (Confirm)</label>
                                            <div class="col-sm-9">
                                                <div class="form-line">
                                                    <input type="password" class="form-control"  name="new2" placeholder="New Password (Confirm)" required="" aria-required="true">
                                                </div>
                                            </div>
                                        </div>

                                        <div class="form-group">
                                            <div class="col-sm-offset-3 col-sm-9">
                                                <button type="submit" class="btn btn-danger">SUBMIT</button>
                                            </div>
                                        </div>
                                    </form>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
@endsection
@section("footerJs")
    @parent
@endsection

resources/views/Module/userOrders.blade.php
@extends('layouts/app')
@section('title','user')
@section('topCss')
    @parent
     <link href="{{ URL::asset("plugins/jquery-datatable/skin/bootstrap/css/dataTables.bootstrap.css")}}" rel="stylesheet">

@endsection

@section('topJs')
    @parent

@endsection
@section("header")
    @parent

@endsection
@section("menu")
    @parent

@endsection
@section('content')
    <section class="content">
        <div class="container-fluid">
            <div class="block-header">
                <h2>DASHBOARD</h2>
            </div>
             <div class="row clearfix">
                <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                    <div class="card">
                        <div class="header">
                            <h2>
                                ORDERS TABLE
                            </h2>
                            <ul class="header-dropdown m-r--5">
                                <li class="dropdown">
                                    <a href="javascript:void(0);" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
                                        <i class="material-icons">more_vert</i>
                                    </a>
                                    <ul class="dropdown-menu pull-right">
                                        <li><a href="javascript:void(0);">Action</a></li>
                                        <li><a href="javascript:void(0);">Another action</a></li>
                                        <li><a href="javascript:void(0);">Something else here</a></li>
                                    </ul>
                                </li>
                            </ul>
                        </div>
                        @if(session()->get('success'))
                            <div class="alert alert-success">
                                {{ session()->get('success') }}
                            </div><br />
                        @endif
                        <div class="body">
                            <div class="table-responsive">
                                <table class="table table-bordered table-striped table-hover dataTable js-exportable">
                                    <thead>
                                    <tr>
                                        <th>Id</th>
                                        <th>Delivery DateTime</th>
                                        <th>Product quantity</th>
                                        <th>Total price</th>
                                        <th>status_id</th>
                                        <th>Created_at</th>
                                        <th>Updated_at</th>
                                            <th>Option</th>
                                            <th>Option</th>

                                        <th>Option</th>

                                    </tr>
                                    </thead>
                                    <tfoot>
                                    <tr>
                                        <th>Id</th>
                                        <th>Delivery DateTime</th>
                                        <th>Product quantity</th>
                                        <th>Total price</th>
                                        <th>status_id</th>
                                        <th>Created_at</th>
                                        <th>Updated_at</th>
                                         <th>Option</th>
                                         <th>Check</th>
                                        <th>Option</th>
                                    </tr>
                                    </tfoot>
                                    <tbody>

                                    @foreach($orders  as $order)
                                        <tr>
                                            <td tabindex="1">{{$order->id}}</td>
                                            <td tabindex="1">{{$order->delivery_date_time}}</td>
                                            <td tabindex="1">{{$order->product_quantity}}</td>
                                            <td tabindex="1">{{$order->total_price}}</td>
                                            <td tabindex="1">{{$order->delivery_status_id}}</td>
                                            <td tabindex="1">{{$order->created_at}}</td>
                                            <td tabindex="1">{{$order->updated_at}}</td>

                                            @if($order->delivery_status_id=='1')
                                                <td tabindex="1"><a href="{{action('OrdersController@edit',$order->id)}}" type="submit" class="btn btn-primary waves-effect">Modifier</a></td>
                                                <form  action="{{action('OrdersController@modif',$order->id)}}" method="post">
                                                    {{csrf_field()}}
                                                    <td tabindex="1"><button type="submit" class="btn btn-primary waves-effect">Livré</button></td>
                                                </form>


                                            <td tabindex="1">

                                                <form  action="{{action('OrdersController@destroy',$order->id)}}" method="post">
                                                    {{csrf_field()}}
                                                    <input name="_method" type="hidden" value="DELETE">
                                                    <button type="submit" class="btn btn-primary waves-effect">Supprimer</button>
                                                </form>

                                            </td>
                                            @endif
                                            @if($order->delivery_status_id=='2')
                                                <td tabindex="1">
                                                    <button type="button" class="btn btn-success waves-effect">
                                                        <i style="top:0px" class="material-icons">check_circle</i>
                                                    </button>
                                                </td>
                                            @endif
                                            @if($order->delivery_status_id=='3')
                                                <td tabindex="1">
                                                    <a  href="{{action('OrdersController@edit',$order->id)}}" type="submit"  class="btn bg-red waves-effect">
                                                        <i class="material-icons">trending_up</i>
                                                        <span>en cours</span>
                                                    </a>
                                                </td>
                                            @endif
                                        </tr>
                                    @endforeach

                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </div>
                </div>
            </div>

        </div>
    </section>
@endsection
@section("footerJs")
    @parent
    <!-- Jquery DataTable Plugin Js -->
    <script src="{{ URL::asset("plugins/jquery-datatable/jquery.dataTables.js")}}"></script>
    <script src="{{ URL::asset("plugins/jquery-datatable/skin/bootstrap/js/dataTables.bootstrap.js")}}"></script>
    <script src="{{ URL::asset("plugins/jquery-datatable/extensions/export/dataTables.buttons.min.js")}}"></script>
    <script src="{{ URL::asset("plugins/jquery-datatable/extensions/export/buttons.flash.min.js")}}"></script>
    <script src="{{ URL::asset("plugins/jquery-datatable/extensions/export/jszip.min.js")}}"></script>
    <script src="{{ URL::asset("plugins/jquery-datatable/extensions/export/pdfmake.min.js")}}"></script>
    <script src="{{ URL::asset("plugins/jquery-datatable/extensions/export/vfs_fonts.js")}}"></script>
    <script src="{{ URL::asset("plugins/jquery-datatable/extensions/export/buttons.html5.min.js")}}"></script>
    <script src="{{ URL::asset("plugins/jquery-datatable/extensions/export/buttons.print.min.js")}}"></script>

    <script src="{{ URL::asset("js/pages/tables/jquery-datatable.js")}}"></script>
@endsection

resources/views/Module/users.blade.php
@extends('layouts/app')
@section('title','user')
@section('topCss')
    @parent
     <link href="{{ URL::asset("plugins/jquery-datatable/skin/bootstrap/css/dataTables.bootstrap.css")}}" rel="stylesheet">

@endsection

@section('topJs')
    @parent

@endsection
@section("header")
    @parent

@endsection
@section("menu")
    @parent

@endsection
@section('content')
    <section class="content">
        <div class="container-fluid">
            <div class="block-header">
                <h2>DASHBOARD</h2>
            </div>
             <div class="row clearfix">
                <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                    <div class="card">
                        <div class="header">
                            <h2>
                                PRODUCT TABLE
                            </h2>
                            <ul class="header-dropdown m-r--5">
                                <li class="dropdown">
                                    <a href="javascript:void(0);" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
                                        <i class="material-icons">more_vert</i>
                                    </a>
                                    <ul class="dropdown-menu pull-right">
                                        <li><a href="javascript:void(0);">Action</a></li>
                                        <li><a href="javascript:void(0);">Another action</a></li>
                                        <li><a href="javascript:void(0);">Something else here</a></li>
                                    </ul>
                                </li>
                            </ul>
                        </div>
                        @if(session()->get('success'))
                            <div class="alert alert-success">
                                {{ session()->get('success') }}
                            </div><br />
                        @endif
                        <div class="body">
                            <div class="table-responsive">
                                <table class="table table-bordered table-striped table-hover dataTable js-exportable">
                                    <thead>
                                    <tr>
                                        <th>id</th>
                                        <th>name</th>
                                        <th>email</th>
                                        <th>phone</th>
                                        <th>delete</th>
                                        <th>commande</th>
                                    </tr>
                                    </thead>
                                    <tfoot>
                                    <tr>
                                        <th>id</th>
                                        <th>name</th>
                                        <th>email</th>
                                        <th>phone</th>
                                        <th>delete</th>
                                        <th>commande</th>
                                    </tr>
                                    </tfoot>
                                    <tbody>

                                    @foreach($users  as $u)

                                        <tr>
                                            <td tabindex="1">{{$u->id}}</td>
                                            <td tabindex="1">{{$u->name}}</td>
                                            <td tabindex="1">{{$u->email}}</td>
                                            <td tabindex="1">{{$u->phone}}</td>

                                            <td tabindex="1">
                                                <form  action="{{route('users.destroy',$u->id)}}" method="post">
                                                    {{csrf_field()}}
                                                    <input name="_method" type="hidden" value="DELETE">
                                                    <button type="submit" class="btn btn-primary waves-effect">Supprimer</button>
                                                </form>
                                            </td>
                                            <td tabindex="1">
                                                {{--<a href="{{action('UsersController@find',$u->id)}}" type="submit" class="btn btn-primary waves-effect">commandes</a>--}}
                                                <a type="submit"  class="btn btn-dark" href="{{ route('find',$u->id)}}">En savoir plus</a>

                                                {{--<form method="post" action="{{ URL::asset('/find',$u->id) }}">--}}
                                                    {{--@csrf--}}

                                                    {{--<button type="submit" class="btn btn-primary waves-effect">show commande</button>--}}
                                                {{--</form>--}}
                                            </td>
                                        </tr>
                                    @endforeach

                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </div>
                </div>
            </div>

        </div>
    </section>
@endsection
@section("footerJs")
    @parent
    <!-- Jquery DataTable Plugin Js -->
    <script src="{{ URL::asset("plugins/jquery-datatable/jquery.dataTables.js")}}"></script>
    <script src="{{ URL::asset("plugins/jquery-datatable/skin/bootstrap/js/dataTables.bootstrap.js")}}"></script>
    <script src="{{ URL::asset("plugins/jquery-datatable/extensions/export/dataTables.buttons.min.js")}}"></script>
    <script src="{{ URL::asset("plugins/jquery-datatable/extensions/export/buttons.flash.min.js")}}"></script>
    <script src="{{ URL::asset("plugins/jquery-datatable/extensions/export/jszip.min.js")}}"></script>
    <script src="{{ URL::asset("plugins/jquery-datatable/extensions/export/pdfmake.min.js")}}"></script>
    <script src="{{ URL::asset("plugins/jquery-datatable/extensions/export/vfs_fonts.js")}}"></script>
    <script src="{{ URL::asset("plugins/jquery-datatable/extensions/export/buttons.html5.min.js")}}"></script>
    <script src="{{ URL::asset("plugins/jquery-datatable/extensions/export/buttons.print.min.js")}}"></script>

    <script src="{{ URL::asset("js/pages/tables/jquery-datatable.js")}}"></script>
@endsection