routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

//Route::get('/', function () {
//    return view('welcome');
//});

Auth::routes();

    Route::get('/home', ['as' => 'index', 'uses' => 'IndexController@showIndex']);
    Route::get('/contact', ['as' => 'contact', 'uses' => 'IndexController@contact']);
    Route::get('/messages/{email}', ['as' => 'messages', 'uses' => 'ContactController@messages']);

    Route::get('/adminMap', 'ZoneController@show');
    Route::get('/clientMap', 'ZoneController@showClient');
    Route::get('/', ['as' => 'index', 'uses' => 'IndexController@showIndex']);
    Route::post('send', ['as' => 'send', 'uses' => 'ContactController@send']);
//
Route::get('/deleteMsg/{id}',['as'=>'deleteMsg','uses'=>'ContactController@delete']);

    Route::get('/categ', ['as' => 'listing', 'uses' => 'CategorieController@showCategorie']);

    //Route::get('/home', 'HomeController@index')->name('home');
    Route::get('/home', ['as' => 'index', 'uses' => 'IndexController@showIndex']);

    Route::get('/map', 'map@show');
    Route::get('/profile', 'profileController@showProfile');

    Route::get('/', ['as' => 'index', 'uses' => 'IndexController@showIndex']);


    Route::get('/categ', ['as' => 'listing', 'uses' => 'CategorieController@showCategorie']);

//Route::get('/editCateg',['as'=>'listing','uses'=>'CategorieController@editCategorie']);
//Route::get('/addCateg',['as'=>'listing','uses'=>'CategorieController@addCategorie']);

    Route::get('/listProd', ['as' => 'listing', 'uses' => 'ProduitController@showProduit']);


    Route::get('/editProd/{id}', ['as' => 'listing', 'uses' => 'ProduitController@edit']);
    Route::post('/editProd/{id}', 'ProduitController@update');
    Route::post('/modif/{id}', 'OrdersController@modif');

    Route::get('/addProd', ['as' => 'listing', 'uses' => 'ProduitController@addProduit']);
    Route::post('/addProd', 'ProduitController@store');

//Route::get('/delete/{id}',['as'=>'listing','uses'=>'ProduitController@destroy']);
//Route::ressource('produit','ProduitController');

    Route::delete('/delete/{id}', 'ProduitController@destroy');
    Route::get('/order', 'OrdersController@show');


    Route::get('/editProd', ['as' => 'listing', 'uses' => 'ProduitController@editProduit']);
    Route::get('/addProd', ['as' => 'listing', 'uses' => 'ProduitController@addProduit']);
    Route::resource('categorie', 'CategorieController');
    Route::resource('zone', 'ZoneController');
    Route::resource('payment', 'PaymentMethodController');

    Route::delete('/delete/{id}', 'ProduitController@destroy');
    Route::get('/recette', 'RecetteController@show');
    Route::post('/filter', 'RecetteController@filter');
    Route::resource('categorie', 'CategorieController');
    Route::resource('orders', 'OrdersController');
    Route::resource('users', 'UsersController');
//Route::get('/find/{id}','UsersController@find');

    Route::get('/find/{id}', ['as' => 'find', 'uses' => 'UsersController@find']);
    Route::post('/profileSetting/{id}', ['as' => 'profileSetting', 'uses' => 'profileController@profileSetting']);
    Route::post('/changePassword/{id}', ['as' => 'changePassword', 'uses' => 'profileController@changePassword']);
//Route::resource('recette', 'RecetteController');
    Route::get('/showlivre', 'OrdersController@showLivre');

app/Http/Controllers/map.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class map extends Controller
{
    public function __construct()
    {
         parent::__construct();
    }

    public
    function show()
    {
        return view('Module.map');
    }
}

resources/views/Module/Map/adminMap.blade.php
@extends('layouts.app')
@section('title','map')
@section('topCss')
    @parent

@endsection

@section('topJs')
    @parent

@endsection
@section("header")
    @parent

@endsection
@section("menu")
    @parent

@endsection
@section('content')
    <section class="content">
        <div class="container-fluid">
            <div class="block-header">
                <h2>DASHBOARD</h2>
            </div>
            <div class="row clearfix">
                <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                    <div class="card">
                        <div class="header">
                            <h2>
                                ADMIN MAP
                            </h2>
                            <ul class="header-dropdown m-r--5">
                                <li class="dropdown">
                                    <a href="javascript:void(0);" class="dropdown-toggle" data-toggle="dropdown"
                                       role="button" aria-haspopup="true" aria-expanded="false">
                                        <i class="material-icons">more_vert</i>
                                    </a>
                                    <ul class="dropdown-menu pull-right">
                                        <li><a href="javascript:void(0);">Action</a></li>
                                        <li><a href="javascript:void(0);">Another action</a></li>
                                        <li><a href="javascript:void(0);">Something else here</a></li>
                                    </ul>
                                </li>
                            </ul>
                        </div>
                        <div class="body">
                            <div id="gmap_basic_example" class="gmap"></div>
                            <div id="info"></div>
                            <form id="form" method="post" action="{{route('zone.store')}}">
                                @csrf
                                <button type="submit" id="myField" name="polygone"
                                        class="btn bg-light-green waves-effect">
                                    <i class="material-icons">save</i>
                                    <span>SAVE COORDS</span>
                                </button>

                            </form>
                        </div>
                    </div>
                </div>
            </div>
            @section("footerJs")
                @parent

                <script>

                    var geocoder;

                    var polygonArray = [];

                    function initMap() {
                        var map = new google.maps.Map(document.getElementById('gmap_basic_example'), {
                            center: {lat: 36.818338, lng: 10.178565},
                            zoom: 17
                        });
                        // Marker.
                        var marker = new google.maps.Marker({
                            position: {lat: 36.818338, lng: 10.178565},
                            animation: google.maps.Animation.DROP,
                            map: map,
                            label: {text: "La caléche!", color: "white"}
                        });
                        var drawingManager = new google.maps.drawing.DrawingManager({
                            drawingMode: google.maps.drawing.OverlayType.MARKER,
                            drawingControl: true,
                            drawingControlOptions: {
                                position: google.maps.ControlPosition.TOP_CENTER,
                                drawingModes: ['polygon']
                            },
                            markerOptions: {icon: 'https://developers.google.com/maps/documentation/javascript/examples/full/images/beachflag.png'},
                            circleOptions: {
                                fillColor: '#ffff00',
                                fillOpacity: 1,
                                strokeWeight: 5,
                                clickable: false,
                                editable: true,
                                zIndex: 1
                            }
                        });

                        drawingManager.setMap(map);

                        $('#form').hide();
                        google.maps.event.addListener(drawingManager, 'polygoncomplete', function (e) {
                            document.getElementById('info').innerHTML += "polygon points:" + "<br>";
                            for (var i = 0; i < e.getPath().getLength(); i++) {
                                document.getElementById('info').innerHTML += e.getPath().getAt(i).toUrlValue(6) + "<br>";
                            }
                            var coordinates = (e.getPath().getArray()) + '';
                            {{--document.getElementById('info').innerHTML+="<a href=\"{{ url('/zone')}}\"  type=\"submit\" class=\"btn bg-light-green waves-effect\"><i class=\"material-icons\">chat</i><span>CHAT</span></a>";--}}
                            $('#form').show();
                            document.getElementById('myField').setAttribute('value', coordinates);

                            console.log(coordinates);
                        });


                    }
                </script>


        </div>
    </section>
@endsection
@section("footerJs")
    @parent


@endsection

resources/views/Module/Map/clientMap.blade.php
@extends('layouts.app')
@section('title','map')
@section('topCss')
    @parent

@endsection

@section('topJs')
    @parent

@endsection
@section("header")
    @parent

@endsection
@section("menu")
    @parent

@endsection
@section('content')
    <section class="content">
        <div class="container-fluid">
            <div class="block-header">
                <h2>DASHBOARD</h2>
            </div>
            <!-- Basic Example -->
            <div class="row clearfix">
                <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                    <div class="card">
                        <div class="header">
                            <h2>
                                CLIENT MAP
                            </h2>
                            <ul class="header-dropdown m-r--5">
                                <li class="dropdown">
                                    <a href="javascript:void(0);" class="dropdown-toggle" data-toggle="dropdown"
                                       role="button" aria-haspopup="true" aria-expanded="false">
                                        <i class="material-icons">more_vert</i>
                                    </a>
                                    <ul class="dropdown-menu pull-right">
                                        <li><a href="javascript:void(0);">Action</a></li>
                                        <li><a href="javascript:void(0);">Another action</a></li>
                                        <li><a href="javascript:void(0);">Something else here</a></li>
                                    </ul>
                                </li>
                            </ul>
                        </div>
                        <div class="body">
                            <div id="map" class="gmap"></div>

                        </div>
                    </div>
                </div>
            </div>
            <!-- #END# Basic Example -->
            @section("footerJs")
                @parent
                <script>


                    function initMap() {

                        var map = new google.maps.Map(document.getElementById('map'), {
                            zoom: 17,
                            center: {lat: 36.818338, lng: 10.178565},
                            mapTypeId: 'terrain'
                        });


                        var Coords = [
                                @for($i=0;$i<count($poly); $i=$i+2)
                            {
                                lat: parseFloat(['{{$poly[$i]}}']), lng: parseFloat(['{{$poly[$i+1]}}'])
                            },
                            @endfor
                        ];
                        console.log('cord', Coords);


                        // var Coords = [
                        // {lat:36.81908990932413 , lng: 10.177321646491464},
                        // {lat:36.81916720824955 , lng: 10.179703448096689},
                        // {lat:36.81845433742188 , lng: 10.176871035376962}
                        // ];

                        // Construct the polygon.
                        var zone = new google.maps.Polygon({
                            paths: Coords,
                            strokeColor: '#FF0000',
                            strokeOpacity: 0.8,
                            strokeWeight: 2,
                            fillColor: '#FF0000',
                            fillOpacity: 0.35
                        });

                        // Marker.
                        var marker = new google.maps.Marker({
                            position: {lat: 36.818338, lng: 10.178565},
                            animation: google.maps.Animation.DROP,
                            map: map,
                            label: {text: "La caléche!", color: "white"}
                        });
                        // Marker.
                        var lastPosition = {lat: 36.818166, lng: 10.179091};
                        var marker2 = new google.maps.Marker({
                            position: {lat: 36.818166, lng: 10.179091},

                            animation: google.maps.Animation.DROP,
                            draggable: true,
                            map: map,
                            label: {text: "My place!", color: "white"}
                        });
                        var infowindow = new google.maps.InfoWindow({
                            content: "<strong>La Calèche</strong>, Avenue de La Liberté, Jeanne d'Arc"
                        });
                        marker.addListener('click', function () {
                            infowindow.open(map, marker);
                        });
                        google.maps.event.addListener(marker2, 'dragend', function (e) {

                            if (google.maps.geometry.poly.containsLocation(e.latLng, zone)) {
                                alert(marker2.getPosition());

                            }
                            else {
                                alert("Out of zone");
                                marker2.setPosition(lastPosition);
                            }

                        });
                        zone.setMap(map);

                    }

                </script>


        </div>
    </section>
@endsection
{{--@section("footerJs")--}}
{{--@parent--}}


{{--@endsection--}}