routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

//Route::get('/', function () {
//    return view('welcome');
//});

Auth::routes();

    Route::get('/home', ['as' => 'index', 'uses' => 'IndexController@showIndex']);
    Route::get('/contact', ['as' => 'contact', 'uses' => 'IndexController@contact']);
    Route::get('/messages/{email}', ['as' => 'messages', 'uses' => 'ContactController@messages']);

    Route::get('/adminMap', 'ZoneController@show');
    Route::get('/clientMap', 'ZoneController@showClient');
    Route::get('/', ['as' => 'index', 'uses' => 'IndexController@showIndex']);
    Route::post('send', ['as' => 'send', 'uses' => 'ContactController@send']);
//
Route::get('/deleteMsg/{id}',['as'=>'deleteMsg','uses'=>'ContactController@delete']);

    Route::get('/categ', ['as' => 'listing', 'uses' => 'CategorieController@showCategorie']);

    //Route::get('/home', 'HomeController@index')->name('home');
    Route::get('/home', ['as' => 'index', 'uses' => 'IndexController@showIndex']);

    Route::get('/map', 'map@show');
    Route::get('/profile', 'profileController@showProfile');

    Route::get('/', ['as' => 'index', 'uses' => 'IndexController@showIndex']);


    Route::get('/categ', ['as' => 'listing', 'uses' => 'CategorieController@showCategorie']);

//Route::get('/editCateg',['as'=>'listing','uses'=>'CategorieController@editCategorie']);
//Route::get('/addCateg',['as'=>'listing','uses'=>'CategorieController@addCategorie']);

    Route::get('/listProd', ['as' => 'listing', 'uses' => 'ProduitController@showProduit']);


    Route::get('/editProd/{id}', ['as' => 'listing', 'uses' => 'ProduitController@edit']);
    Route::post('/editProd/{id}', 'ProduitController@update');
    Route::post('/modif/{id}', 'OrdersController@modif');

    Route::get('/addProd', ['as' => 'listing', 'uses' => 'ProduitController@addProduit']);
    Route::post('/addProd', 'ProduitController@store');

//Route::get('/delete/{id}',['as'=>'listing','uses'=>'ProduitController@destroy']);
//Route::ressource('produit','ProduitController');

    Route::delete('/delete/{id}', 'ProduitController@destroy');
    Route::get('/order', 'OrdersController@show');


    Route::get('/editProd', ['as' => 'listing', 'uses' => 'ProduitController@editProduit']);
    Route::get('/addProd', ['as' => 'listing', 'uses' => 'ProduitController@addProduit']);
    Route::resource('categorie', 'CategorieController');
    Route::resource('zone', 'ZoneController');
    Route::resource('payment', 'PaymentMethodController');

    Route::delete('/delete/{id}', 'ProduitController@destroy');
    Route::get('/recette', 'RecetteController@show');
    Route::post('/filter', 'RecetteController@filter');
    Route::resource('categorie', 'CategorieController');
    Route::resource('orders', 'OrdersController');
    Route::resource('users', 'UsersController');
//Route::get('/find/{id}','UsersController@find');

    Route::get('/find/{id}', ['as' => 'find', 'uses' => 'UsersController@find']);
    Route::post('/profileSetting/{id}', ['as' => 'profileSetting', 'uses' => 'profileController@profileSetting']);
    Route::post('/changePassword/{id}', ['as' => 'changePassword', 'uses' => 'profileController@changePassword']);
//Route::resource('recette', 'RecetteController');
    Route::get('/showlivre', 'OrdersController@showLivre');

resources/views/Module/payment/add.blade.php
@extends('layouts/app')
@section('title','paiement')
@section('topCss')
    @parent

@endsection

@section('topJs')
    @parent

@endsection
@section("header")
    @parent

@endsection
@section("menu")
    @parent

@endsection
@section('content')
    <section class="content">
        <div class="container-fluid">
            <div class="block-header">
                <h2>DASHBOARD</h2>
            </div>


            <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                <div class="card">
                    <div class="header">
                        <h2>AJOUT PAYMENT METHOD</h2>
                        <ul class="header-dropdown m-r--5">
                            <li class="dropdown">
                                <a href="javascript:void(0);" class="dropdown-toggle" data-toggle="dropdown"
                                   role="button" aria-haspopup="true" aria-expanded="false">
                                    <i class="material-icons">more_vert</i>
                                </a>
                                <ul class="dropdown-menu pull-right">
                                    <li><a href="javascript:void(0);" class=" waves-effect waves-block">Action</a></li>
                                    <li><a href="javascript:void(0);" class=" waves-effect waves-block">Another
                                            action</a></li>
                                    <li><a href="javascript:void(0);" class=" waves-effect waves-block">Something else
                                            here</a></li>
                                </ul>
                            </li>
                        </ul>
                    </div>
                    <div class="body">
                        @if ($errors->any())
                            <div class="alert alert-danger">
                                <ul>
                                    @foreach ($errors->all() as $error)
                                        <li>{{ $error }}</li>
                                    @endforeach
                                </ul>
                            </div><br/>
                        @endif
                        <form method="post" action="{{ route('payment.store') }}" enctype="multipart/form-data">
                            @csrf
                            <div class="form-group form-float">
                                <div class="form-line">
                                    <input type="text" class="form-control" name="name" maxlength="20" minlength="3"
                                           required="" aria-required="true">
                                    <label class="form-label">Name</label>
                                </div>
                                <div class="help-info">Min. 3, Max. 10 characters</div>
                            </div>


                            <button class="btn btn-primary waves-effect" type="submit">AJOUTER</button>
                        </form>
                    </div>
                </div>
            </div>


        </div>
    </section>
@endsection
@section("footerJs")
    @parent
@endsection

resources/views/Module/payment/edit.blade.php
@extends('layouts/app')
@section('title','paiement')
@section('topCss')
    @parent

    <link href="{{ URL::asset("../../plugins/bootstrap-select/css/bootstrap-select.css")}}" rel="stylesheet"/>
@endsection

@section('topJs')
    @parent

@endsection
@section("header")
    @parent

@endsection
@section("menu")
    @parent

@endsection
@section('content')
    <section class="content">
        <div class="container-fluid">
            <div class="block-header">
                <h2>DASHBOARD</h2>
            </div>


            <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                <div class="card">
                    <div class="header">
                        <h2>MODIFICATION COMMMANDE</h2>
                        <ul class="header-dropdown m-r--5">
                            <li class="dropdown">
                                <a href="javascript:void(0);" class="dropdown-toggle" data-toggle="dropdown"
                                   role="button" aria-haspopup="true" aria-expanded="false">
                                    <i class="material-icons">more_vert</i>
                                </a>
                                <ul class="dropdown-menu pull-right">
                                    <li><a href="javascript:void(0);" class=" waves-effect waves-block">Action</a></li>
                                    <li><a href="javascript:void(0);" class=" waves-effect waves-block">Another
                                            action</a></li>
                                    <li><a href="javascript:void(0);" class=" waves-effect waves-block">Something else
                                            here</a></li>
                                </ul>
                            </li>
                        </ul>
                    </div>
                    <div class="body">
                        @if($errors->any())
                            <div class="alert alert-danger">
                                <ul>
                                    @foreach($errors->all() as $error)
                                        <li>{{$error}}</li>
                                    @endforeach
                                </ul>
                            </div><br/>
                        @endif
                        <form method="post" action="{{ route('payment.update', $payment->id) }}">
                            @method('PATCH')
                            @csrf

                            <div class="form-group form-float">
                                <div class="form-line">
                                    <input type="text" class="form-control" name="name" required=""
                                           value="{{$payment->name}}" aria-required="true">
                                    <label class="form-label">Name</label>
                                </div>
                            </div>


                            <button class="btn btn-primary waves-effect" type="submit">SUBMIT</button>
                        </form>
                    </div>
                </div>
            </div>


        </div>
    </section>
@endsection
@section("footerJs")
    @parent
@endsection

resources/views/Module/payment/listing.blade.php
@extends('layouts/app')
@section('title','paiement')
@section('topCss')
    @parent
     <link href="{{ URL::asset("plugins/jquery-datatable/skin/bootstrap/css/dataTables.bootstrap.css")}}" rel="stylesheet">

@endsection

@section('topJs')
    @parent

@endsection
@section("header")
    @parent

@endsection
@section("menu")
    @parent

@endsection
@section('content')
    <section class="content">
        <div class="container-fluid">
            <div class="block-header">
                <h2>DASHBOARD</h2>
            </div>
             <div class="row clearfix">
                <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                    <div class="card">
                        <div class="header">
                            <h2>
                                EXPORTABLE TABLE
                            </h2>
                            <ul class="header-dropdown m-r--5">
                                <li class="dropdown">
                                    <a href="javascript:void(0);" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
                                        <i class="material-icons">more_vert</i>
                                    </a>
                                    <ul class="dropdown-menu pull-right">
                                        <li><a href="javascript:void(0);">Action</a></li>
                                        <li><a href="javascript:void(0);">Another action</a></li>
                                        <li><a href="javascript:void(0);">Something else here</a></li>
                                    </ul>
                                </li>
                            </ul>
                        </div>
                        @if(session()->get('success'))
                            <div class="alert alert-success">
                                {{ session()->get('success') }}
                            </div><br />
                        @endif
                        <div class="body">
                            <div class="table-responsive">
                                <table class="table table-bordered table-striped table-hover dataTable js-exportable">
                                    <thead>
                                    <tr>
                                        <th>id</th>
                                        <th>name</th>
                                        <th>Created_at</th>
                                        <th>Updated_at</th>
                                        <th>Action</th>
                                        <th>Action</th>

                                    </tr>
                                    </thead>
                                    <tfoot>
                                    <tr>
                                        <th>id</th>
                                        <th>name</th>
                                        <th>Created_at</th>
                                        <th>Updated_at</th>
                                        <th>Action</th>
                                        <th>Action</th>

                                    </tr>
                                    </tfoot>
                                    <tbody>

                                    @foreach($payment_method as $p)
                                        <tr>
                                            <td>{{ $p->id }}</td>
                                            <td>{{ $p->name }}</td>
                                            <td>{{ $p->created_at }}</td>
                                            <td>{{ $p->updated_at }}</td>
                                            <form action="{{ route('payment.destroy', $p->id)}}" method="post">
                                                @csrf
                                                @method('DELETE')
                                                <td>
                                                    <button   type="submit" class="btn bg-purple waves-effect">Supprimer</button>
                                                </td>
                                            </form>

                                            <td>
                                                <a href="{{ route('payment.edit',$p->id)}}" type="submit" class="btn bg-pink waves-effect">Modifier</a>
                                            </td>
                                        </tr>
                                    @endforeach

                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </div>
                </div>
            </div>

        </div>
    </section>
@endsection
@section("footerJs")
    @parent
    <!-- Jquery DataTable Plugin Js -->
    <script src="{{ URL::asset("plugins/jquery-datatable/jquery.dataTables.js")}}"></script>
    <script src="{{ URL::asset("plugins/jquery-datatable/skin/bootstrap/js/dataTables.bootstrap.js")}}"></script>
    <script src="{{ URL::asset("plugins/jquery-datatable/extensions/export/dataTables.buttons.min.js")}}"></script>
    <script src="{{ URL::asset("plugins/jquery-datatable/extensions/export/buttons.flash.min.js")}}"></script>
    <script src="{{ URL::asset("plugins/jquery-datatable/extensions/export/jszip.min.js")}}"></script>
    <script src="{{ URL::asset("plugins/jquery-datatable/extensions/export/pdfmake.min.js")}}"></script>
    <script src="{{ URL::asset("plugins/jquery-datatable/extensions/export/vfs_fonts.js")}}"></script>
    <script src="{{ URL::asset("plugins/jquery-datatable/extensions/export/buttons.html5.min.js")}}"></script>
    <script src="{{ URL::asset("plugins/jquery-datatable/extensions/export/buttons.print.min.js")}}"></script>

    <script src="{{ URL::asset("js/pages/tables/jquery-datatable.js")}}"></script>
@endsection